[package]
name = "rofi-pinyin"
version = "0.1.0"
edition = "2021"
description = "hanzi to pinyin"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version="4.4.6", features=["derive"]}
rofi = "0.3.0"
